/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.example.delicious.API.CloudDB;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.EntireEncrypted;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

import java.util.Date;

/**
 * Definition of ObjectType Accounts.
 *
 * @since 2021-07-24
 */
@PrimaryKeys({"idAcc"})
public final class Accounts extends CloudDBZoneObject {
    public Accounts(Class<? extends CloudDBZoneObject> aClass, String idAcc, String nameAcc, String seAcc, String jobAcc, String yearoldAcc, String mpAcc, String phone, String email, String social, String gender) {
        super(aClass);
        this.idAcc = idAcc;
        this.nameAcc = nameAcc;
        this.seAcc = seAcc;
        this.jobAcc = jobAcc;
        this.yearoldAcc = yearoldAcc;
        this.mpAcc = mpAcc;
        this.phone = phone;
        this.email = email;
        this.social = social;
        this.gender = gender;
    }

    private String idAcc;

    private String nameAcc;

    private String seAcc;

    private String jobAcc;

    private String yearoldAcc;

    private String mpAcc;

    public String phone;

    private String email;

    private  String social;

    private String gender;

    public Accounts() {
        super(Accounts.class);
    }

    public void setIdAcc(String idAcc) {
        this.idAcc = idAcc;
    }

    public String getIdAcc() {
        return idAcc;
    }

    public void setNameAcc(String nameAcc) {
        this.nameAcc = nameAcc;
    }

    public String getNameAcc() {
        return nameAcc;
    }

    public void setSeAcc(String seAcc) {
        this.seAcc = seAcc;
    }

    public String getSeAcc() {
        return seAcc;
    }

    public void setJobAcc(String jobAcc) {
        this.jobAcc = jobAcc;
    }

    public String getJobAcc() {
        return jobAcc;
    }

    public void setYearoldAcc(String yearoldAcc) {
        this.yearoldAcc = yearoldAcc;
    }

    public String getYearoldAcc() {
        return yearoldAcc;
    }

    public void setMpAcc(String mpAcc) {
        this.mpAcc = mpAcc;
    }

    public String getMpAcc() {
        return mpAcc;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getSocial() {
        return social;
    }

    public void setSocial(String social) {
        this.social = social;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }
}
