/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.example.delicious.API.CloudDB;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.EntireEncrypted;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

import java.util.Date;

/**
 * Definition of ObjectType DishFavorite.
 *
 * @since 2021-07-25
 */
@PrimaryKeys({"idFD"})
public final class DishFavorite extends CloudDBZoneObject {
    public DishFavorite(Class<? extends CloudDBZoneObject> aClass, String idFD, String idAcc, String idF, String timeLike) {
        super(aClass);
        this.idFD = idFD;
        this.idAcc = idAcc;
        this.idF = idF;
        this.timeLike = timeLike;
    }

    private String idFD;

    private String idAcc;

    private String idF;

    private String timeLike;

    public DishFavorite() {
        super(DishFavorite.class);
    }

    public void setIdFD(String idFD) {
        this.idFD = idFD;
    }

    public String getIdFD() {
        return idFD;
    }

    public void setIdAcc(String idAcc) {
        this.idAcc = idAcc;
    }

    public String getIdAcc() {
        return idAcc;
    }

    public void setIdF(String idF) {
        this.idF = idF;
    }

    public String getIdF() {
        return idF;
    }

    public void setTimeLike(String timeLike) {
        this.timeLike = timeLike;
    }

    public String getTimeLike() {
        return timeLike;
    }

}
