/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.example.delicious.API.CloudDB;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.EntireEncrypted;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

import java.util.Date;

/**
 * Definition of ObjectType FoodInfo.
 *
 * @since 2021-07-24
 */
@PrimaryKeys({"idF"})
public final class FoodInfo extends CloudDBZoneObject {
    public FoodInfo(Class<? extends CloudDBZoneObject> aClass, String idF, String nameF, String avatarF, Text proflieF, String typeF, String amountPF, String timecookF, String authorF, String amountviewF, String amountlikeF, String timeupF) {
        super(aClass);
        this.idF = idF;
        this.nameF = nameF;
        this.avatarF = avatarF;
        this.proflieF = proflieF;
        this.typeF = typeF;
        this.amountPF = amountPF;
        this.timecookF = timecookF;
        this.authorF = authorF;
        this.amountviewF = amountviewF;
        this.amountlikeF = amountlikeF;
        this.timeupF = timeupF;
    }

    private String idF;

    private String nameF;

    private String avatarF;

    private Text proflieF;

    private String typeF;

    private String amountPF;

    private String timecookF;

    private String authorF;

    private String amountviewF;

    private String amountlikeF;

    private String timeupF;

    public FoodInfo() {
        super(FoodInfo.class);
    }

    public void setIdF(String idF) {
        this.idF = idF;
    }

    public String getIdF() {
        return idF;
    }

    public void setNameF(String nameF) {
        this.nameF = nameF;
    }

    public String getNameF() {
        return nameF;
    }

    public void setAvatarF(String avatarF) {
        this.avatarF = avatarF;
    }

    public String getAvatarF() {
        return avatarF;
    }

    public void setProflieF(Text proflieF) {
        this.proflieF = proflieF;
    }

    public Text getProflieF() {
        return proflieF;
    }

    public void setTypeF(String typeF) {
        this.typeF = typeF;
    }

    public String getTypeF() {
        return typeF;
    }

    public void setAmountPF(String amountPF) {
        this.amountPF = amountPF;
    }

    public String getAmountPF() {
        return amountPF;
    }

    public void setTimecookF(String timecookF) {
        this.timecookF = timecookF;
    }

    public String getTimecookF() {
        return timecookF;
    }

    public void setAuthorF(String authorF) {
        this.authorF = authorF;
    }

    public String getAuthorF() {
        return authorF;
    }

    public void setAmountviewF(String amountviewF) {
        this.amountviewF = amountviewF;
    }

    public String getAmountviewF() {
        return amountviewF;
    }

    public void setAmountlikeF(String amountlikeF) {
        this.amountlikeF = amountlikeF;
    }

    public String getAmountlikeF() {
        return amountlikeF;
    }

    public void setTimeupF(String timeupF) {
        this.timeupF = timeupF;
    }

    public String getTimeupF() {
        return timeupF;
    }

}
