/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.example.delicious.API.CloudDB;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.EntireEncrypted;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

import java.util.Date;

/**
 * Definition of ObjectType FoodStep.
 *
 * @since 2021-07-24
 */
@PrimaryKeys({"idStep"})
public final class FoodStep extends CloudDBZoneObject {
    public FoodStep(Class<? extends CloudDBZoneObject> aClass, String idStep, String imgStep, Text contentStep, String idF) {
        super(aClass);
        this.idStep = idStep;
        this.imgStep = imgStep;
        this.contentStep = contentStep;
        this.idF = idF;
    }

    private String idStep;

    private String imgStep;

    private Text contentStep;

    private String idF;

    public FoodStep() {
        super(FoodStep.class);
    }

    public void setIdStep(String idStep) {
        this.idStep = idStep;
    }

    public String getIdStep() {
        return idStep;
    }

    public void setImgStep(String imgStep) {
        this.imgStep = imgStep;
    }

    public String getImgStep() {
        return imgStep;
    }

    public void setContentStep(Text contentStep) {
        this.contentStep = contentStep;
    }

    public Text getContentStep() {
        return contentStep;
    }

    public void setIdF(String idF) {
        this.idF = idF;
    }

    public String getIdF() {
        return idF;
    }

}
